schema_version = "1.0.0"
id = "GamingToolkit"
version = "3.0.0"
name = "Gaming Toolkit"
tagline = "Gaming Toolkit"
maintainer = "Blender Bob"
type = "add-on"
website = "https://github.com/riouxr/Copy-Shapekeys"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]